import type { RoleConfig } from "../types";

export const roleConfigs: Record<string, RoleConfig> = {
  frontend: {
    key: "frontend",
    name: "前端开发",
    rank: "P5",
    salary: 25000,
    techSkill: 65,
    socialSkill: 45,
    innovationSkill: 50,
    hiddenScores: {
      techMatch: 75,
      teamContribution: 55,
      aiAdaptability: 55,
      marketValue: 65,
      health: 80,
      family: 80,
    },
    warnings: 0,
    description: "拥抱变化，快速学习是你的优势",
    skillPoints: 3,
  },
  backend: {
    key: "backend",
    name: "后端开发",
    rank: "P5",
    salary: 26000,
    techSkill: 70,
    socialSkill: 40,
    innovationSkill: 45,
    hiddenScores: {
      techMatch: 72,
      teamContribution: 65,
      aiAdaptability: 45,
      marketValue: 68,
      health: 80,
      family: 80,
    },
    warnings: 0,
    description: "架构复杂，业务深度高，AI难以完全替代",
    skillPoints: 3,
  },
  product: {
    key: "product",
    name: "产品经理",
    rank: "P5",
    salary: 27000,
    techSkill: 45,
    socialSkill: 75,
    innovationSkill: 65,
    hiddenScores: {
      techMatch: 60,
      teamContribution: 80,
      aiAdaptability: 50,
      marketValue: 70,
      health: 80,
      family: 80,
    },
    warnings: 0,
    description: "需要用户理解和沟通，AI难以替代",
    skillPoints: 3,
  },
  designer: {
    key: "designer",
    name: "UI设计师",
    rank: "P5",
    salary: 24000,
    techSkill: 50,
    socialSkill: 50,
    innovationSkill: 75,
    hiddenScores: {
      techMatch: 65,
      teamContribution: 55,
      aiAdaptability: 40,
      marketValue: 60,
      health: 80,
      family: 80,
    },
    warnings: 0,
    description: "AI生成速度快，需要持续提升创意能力",
    skillPoints: 3,
  },
  qa: {
    key: "qa",
    name: "测试工程师",
    rank: "P5",
    salary: 24000,
    techSkill: 60,
    socialSkill: 55,
    innovationSkill: 45,
    hiddenScores: {
      techMatch: 68,
      teamContribution: 70,
      aiAdaptability: 40,
      marketValue: 62,
      health: 80,
      family: 80,
    },
    warnings: 0,
    description: "质量保障需要经验判断，AI难以完全自动化",
    skillPoints: 3,
  },
  data: {
    key: "data",
    name: "数据分析师",
    rank: "P5",
    salary: 26000,
    techSkill: 65,
    socialSkill: 50,
    innovationSkill: 60,
    hiddenScores: {
      techMatch: 70,
      teamContribution: 60,
      aiAdaptability: 55,
      marketValue: 68,
      health: 80,
      family: 80,
    },
    warnings: 0,
    description: "AI会帮你计算，但业务洞察依然依赖人类",
    skillPoints: 3,
  },
};

export default roleConfigs;
